### PR TITLE
Add ‘manual tests’ to publishing process

### PR DESCRIPTION
**Pull request by dedan**
+@pcorpet

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/fex/12)

### CODE REVIEW

**Comment by dedan** [comment]
+@pcorpet 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/fex/12#-:-KDxm-QMQB4TtQVED9Xl:1879340593)*

**Comment by pcorpet** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[setup.py, line 22 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/fex/12#-KDyeTwKcl2haJ5_3JZy:-KDyeTwKcl2haJ5_3JZz:-1827589714) ([raw file](https://github.com/bayesimpact/fex/blob/38643f6fc55568d53f48303dc659ea6d5f15725e/setup.py#L22)):*
Either make it relative to here tests/manual_tests.md or an absolute URL (preferred): https://github.com....

---

*[tests/manual_tests.md, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/fex/12#-KDyecoeWM6BxVtQ-4gp:-KDyecoeWM6BxVtQ-4gq:1978685730) ([raw file](https://github.com/bayesimpact/fex/blob/38643f6fc55568d53f48303dc659ea6d5f15725e/tests/manual_tests.md#L9)):*
Can you add more precise steps on how to check those please?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/fex/12)*

**Comment by dedan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[setup.py, line 22 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/fex/12#-KDyeTwKcl2haJ5_3JZy:-KE0LP7Pi1LZfhx2i8Bt:-499146009) ([raw file](https://github.com/bayesimpact/fex/blob/38643f6fc55568d53f48303dc659ea6d5f15725e/setup.py#L22)):*
Done.

---

*[tests/manual_tests.md, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/fex/12#-KDyecoeWM6BxVtQ-4gp:-KE0LOQP2TzjOtg-0aXC:-499146009) ([raw file](https://github.com/bayesimpact/fex/blob/38643f6fc55568d53f48303dc659ea6d5f15725e/tests/manual_tests.md#L9)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/fex/12)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/manual_tests.md, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/fex/12#-KDyecoeWM6BxVtQ-4gp:-KE0LqddiFEHMcfhpAJU:-145566025) ([raw file](https://github.com/bayesimpact/fex/blob/38643f6fc55568d53f48303dc659ea6d5f15725e/tests/manual_tests.md#L9)):*
Please add quite precise instructions so that anybody can do it:

1. outside of a git repository
- create a folder "foo"
- copy examples/simple_example.py there
- run it "foo/simple_example.py --deploy"
- you should get an error message 

...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/fex/12#-:-KE0M7zILuT3Gvqe3bnh:1417088721)*

**Comment by dedan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/manual_tests.md, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/fex/12#-KDyecoeWM6BxVtQ-4gp:-KE0RuJym9-dzgZpL2_o:-499146009) ([raw file](https://github.com/bayesimpact/fex/blob/38643f6fc55568d53f48303dc659ea6d5f15725e/tests/manual_tests.md#L9)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/fex/12)*

**Pull request merged**
