### PR TITLE
concatenates data frames along the correct axis.

### PR DESCRIPTION
**Pull request by mjamei**
we want to keep the indices and concat along columns.

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/fex/15)

### CODE REVIEW

**Comment by AlexNisnevich** [comment]
LGTM. @dedan, what do you think?

**Comment by dedan** [comment]
Looks good in general. But could you please add a test that would have failed without the fix?

**Comment by dedan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/fex/15)*

**Comment by AlexNisnevich** [comment]
@dedan: We don't have time to make a test because a test would necessarily be a little complicated to demonstrate the necessity of this, but we need this merged ASAP because sutter is kind of stuck unless we can get this working.

So I'm going to merge now and add an issue to add a test.

**Pull request merged**
